package kube

import "github.com/spf13/cobra"

// KubeCmd groups Teleport Kubernetes access commands.
var KubeCmd = &cobra.Command{
	Use:   "kube",
	Short: "Access Teleport-registered Kubernetes clusters",
	Long: `Commands for accessing Kubernetes clusters registered with Teleport.

The 'token' subcommand is a kubectl exec credential plugin: the kubeconfig
generated by the teleport/kubernetes integration wires kubectl to call it to
obtain short-lived client certificates routed through the Teleport proxy.`,
	FParseErrWhitelist: struct{ UnknownFlags bool }{UnknownFlags: false},
	Args:               cobra.NoArgs,
}
