package kube

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	errUtils "github.com/cloudposse/atmos/errors"
	"github.com/cloudposse/atmos/pkg/auth"
	teleportCloud "github.com/cloudposse/atmos/pkg/auth/cloud/teleport"
	"github.com/cloudposse/atmos/pkg/auth/credentials"
	"github.com/cloudposse/atmos/pkg/auth/types"
	"github.com/cloudposse/atmos/pkg/auth/validation"
	cfg "github.com/cloudposse/atmos/pkg/config"
	"github.com/cloudposse/atmos/pkg/data"
	log "github.com/cloudposse/atmos/pkg/logger"
	"github.com/cloudposse/atmos/pkg/perf"
	"github.com/cloudposse/atmos/pkg/schema"
)

// execCredentialAPIVersion is the Kubernetes exec credential plugin API version.
const execCredentialAPIVersion = "client.authentication.k8s.io/v1beta1"

// initCliConfigFn loads Atmos CLI configuration. Overridable in tests.
var initCliConfigFn = func(info schema.ConfigAndStacksInfo, processStacks bool) (schema.AtmosConfiguration, error) {
	return cfg.InitCliConfig(info, processStacks)
}

// authenticateForTokenFn authenticates an identity and returns credentials. Overridable in tests.
var authenticateForTokenFn = authenticateForToken

// generateKubeCertFn issues a per-cluster Teleport kube certificate. Overridable in tests.
var generateKubeCertFn = generateKubeCert

// tokenCmd generates a short-lived Teleport Kubernetes client credential for kubectl.
var tokenCmd = &cobra.Command{
	Use:   "token",
	Short: "Generate a Teleport Kubernetes client credential for kubectl",
	Long: `Generate a short-lived Kubernetes client certificate routed through the Teleport proxy.

This command is designed to be used as a kubectl exec credential plugin.
It authenticates using the specified identity, requests a per-cluster
certificate from Teleport, and outputs an ExecCredential JSON object
(with clientCertificateData and clientKeyData) to stdout.

The kubeconfig generated by the teleport/kubernetes integration automatically
configures kubectl to call this command.

Examples:
  # Generate a credential for a cluster (typically called by kubectl)
  atmos teleport kube token --cluster prod-eks

  # Generate a credential using a specific identity
  atmos teleport kube token --cluster prod-eks --identity ci-bot`,

	FParseErrWhitelist: struct{ UnknownFlags bool }{UnknownFlags: false},
	Args:               cobra.NoArgs,
	RunE:               executeTokenCommand,
	// Suppress usage on errors since kubectl invokes this automatically.
	SilenceUsage: true,
}

// execCredential represents the Kubernetes ExecCredential response.
type execCredential struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Status     execCredentialStatus `json:"status"`
}

// execCredentialStatus carries the client certificate, key, and expiry.
//
// Teleport Kubernetes access is mutual-TLS based, so kubectl authenticates with
// a client certificate/key (not a bearer token like EKS).
type execCredentialStatus struct {
	ClientCertificateData string `json:"clientCertificateData"`
	ClientKeyData         string `json:"clientKeyData"`
	ExpirationTimestamp   string `json:"expirationTimestamp"`
}

func executeTokenCommand(cmd *cobra.Command, _ []string) error {
	atmosConfig, err := initCliConfigFn(schema.ConfigAndStacksInfo{}, false)
	if err != nil {
		return fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitConfig, err)
	}
	defer perf.Track(&atmosConfig, "kube.executeTokenCommand")()

	ctx := context.Background()

	clusterName, _ := cmd.Flags().GetString("cluster")
	if clusterName == "" {
		return fmt.Errorf("%w: --cluster is required", errUtils.ErrTeleportKubeCertGeneration)
	}

	identityName := resolveIdentity(cmd)
	log.Debug("Generating Teleport kube credential", "cluster", clusterName, "identity", identityName)

	// Skip integrations to avoid rewriting the kubeconfig during token generation.
	ctx = auth.ContextWithSkipIntegrations(ctx)
	creds, err := authenticateForTokenFn(ctx, &atmosConfig.Auth, atmosConfig.CliConfigPath, identityName)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}

	teleportCreds, ok := creds.(*types.TeleportCredentials)
	if !ok {
		return fmt.Errorf("%w: identity %q did not produce Teleport credentials (got %T)", errUtils.ErrTeleportKubeCertGeneration, identityName, creds)
	}

	kubeCert, err := generateKubeCertFn(ctx, teleportCreds, clusterName)
	if err != nil {
		return fmt.Errorf("%w: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}

	credential := execCredential{
		APIVersion: execCredentialAPIVersion,
		Kind:       "ExecCredential",
		Status: execCredentialStatus{
			ClientCertificateData: kubeCert.TLSCertPEM,
			ClientKeyData:         kubeCert.TLSKeyPEM,
			ExpirationTimestamp:   kubeCert.Expires.UTC().Format(time.RFC3339),
		},
	}

	output, err := json.Marshal(credential)
	if err != nil {
		return fmt.Errorf("%w: failed to marshal ExecCredential: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}

	return data.Write(string(output))
}

// resolveIdentity resolves the identity name from flag, then env var.
func resolveIdentity(cmd *cobra.Command) string {
	identity, _ := cmd.Flags().GetString("identity")
	if identity != "" {
		return identity
	}
	if envIdentity := os.Getenv("ATMOS_IDENTITY"); envIdentity != "" {
		return envIdentity
	}
	return ""
}

// authenticateForToken authenticates an identity and returns its credentials.
func authenticateForToken(ctx context.Context, authConfig *schema.AuthConfig, cliConfigPath, identityName string) (types.ICredentials, error) {
	defer perf.Track(nil, "kube.authenticateForToken")()

	authStackInfo := &schema.ConfigAndStacksInfo{AuthContext: &schema.AuthContext{}}

	credStore := credentials.NewCredentialStoreWithConfig(authConfig)
	validator := validation.NewValidator()

	mgr, err := auth.NewAuthManager(authConfig, credStore, validator, authStackInfo, cliConfigPath)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapFormat, errUtils.ErrFailedToInitializeAuthManager, err)
	}

	if identityName == "" {
		identityName = resolveDefaultIdentity(authConfig)
		if identityName == "" {
			return nil, fmt.Errorf("%w: no identity specified and no default identity found", errUtils.ErrTeleportKubeCertGeneration)
		}
	}

	whoami, err := mgr.Authenticate(ctx, identityName)
	if err != nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, err)
	}
	if whoami.Credentials == nil {
		return nil, fmt.Errorf(errUtils.ErrWrapWithNameAndCauseFormat, errUtils.ErrIdentityAuthFailed, identityName, errUtils.ErrIdentityCredentialsNone)
	}

	return whoami.Credentials, nil
}

// resolveDefaultIdentity finds a default identity from the auth config. When
// exactly one identity is configured it is selected; otherwise empty.
func resolveDefaultIdentity(authConfig *schema.AuthConfig) string {
	if authConfig == nil || len(authConfig.Identities) == 0 {
		return ""
	}
	if len(authConfig.Identities) == 1 {
		for name := range authConfig.Identities {
			return name
		}
	}
	return ""
}

// generateKubeCert issues a per-cluster Teleport kube certificate using the
// Teleport SDK client. Separated behind generateKubeCertFn so the command logic
// is testable without a live cluster.
func generateKubeCert(ctx context.Context, creds *types.TeleportCredentials, clusterName string) (*teleportCloud.KubeCert, error) {
	defer perf.Track(nil, "kube.generateKubeCert")()

	client, err := teleportCloud.NewClient(ctx, creds)
	if err != nil {
		return nil, err
	}
	defer func() { _ = client.Close() }()

	return client.GenerateKubeCert(ctx, teleportCloud.GenerateKubeCertRequest{KubernetesCluster: clusterName})
}

func init() {
	tokenCmd.Flags().String("cluster", "", "Teleport Kubernetes cluster name (required)")
	tokenCmd.Flags().StringP("identity", "i", "", "Atmos identity to authenticate with")
	KubeCmd.AddCommand(tokenCmd)
}
