package teleport

//go:generate go run go.uber.org/mock/mockgen@latest -source=client.go -destination=mock_client_test.go -package=teleport

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"time"

	teleportClient "github.com/gravitational/teleport/api/client"
	"github.com/gravitational/teleport/api/client/proto"
	"github.com/gravitational/teleport/api/utils/keys"

	errUtils "github.com/cloudposse/atmos/errors"
	"github.com/cloudposse/atmos/pkg/auth/types"
	"github.com/cloudposse/atmos/pkg/perf"
)

// defaultKubeCertTTL is the fallback certificate lifetime used when a request
// does not specify one.
const defaultKubeCertTTL = time.Hour

// rsaKeyBits is the key size used for generated kube certs. RSA 2048 is
// accepted by Teleport's default/legacy signature-algorithm suite; suite-aware
// key selection (ECDSA for balanced-v1) is a live-cluster refinement.
const rsaKeyBits = 2048

// dialTimeout bounds how long client construction waits to reach the proxy.
const dialTimeout = 30 * time.Second

// Client abstracts the Teleport API SDK so that providers, identities, and
// integrations can be unit-tested without a live Teleport cluster.
//
// Production implementations wrap github.com/gravitational/teleport/api/client.
// Test implementations are generated by mockgen (mock_client_test.go).
//
// The Client is constructed per-invocation from TeleportCredentials, so
// implementations should be cheap to instantiate. Long-lived connection
// pooling, if needed, lives inside the SDK-backed implementation.
type Client interface {
	// Ping verifies connectivity and returns the cluster's authority info.
	// Used by Validate() on credentials to confirm a cert is still accepted.
	Ping(ctx context.Context) (*PingResponse, error)

	// GenerateKubeCert issues a per-kubernetes-cluster TLS certificate using
	// the current credentials. Returns the new cert/key/CA suitable for
	// embedding in a kubeconfig entry.
	//
	// req.KubernetesCluster names the Teleport-registered k8s cluster.
	// req.TTL is the requested cert lifetime.
	GenerateKubeCert(ctx context.Context, req GenerateKubeCertRequest) (*KubeCert, error)

	// Close releases any resources held by the client.
	Close() error
}

// PingResponse summarizes a Teleport proxy ping response. We intentionally
// expose only the fields Atmos uses, so the SDK type doesn't leak through the
// abstraction.
type PingResponse struct {
	ClusterName     string
	ServerVersion   string
	ProxyPublicAddr string
}

// GenerateKubeCertRequest carries the parameters Atmos needs for issuing a
// per-kube-cluster certificate via the Teleport SDK.
type GenerateKubeCertRequest struct {
	// KubernetesCluster names the Teleport-registered k8s cluster (required).
	KubernetesCluster string

	// TTL is the requested certificate lifetime. Zero means "use Teleport's
	// default for this identity".
	TTL string

	// Roles optionally narrows the role set requested for this cert. Empty
	// means "use all roles in the underlying credentials".
	Roles []string
}

// KubeCert holds the certificate material returned by GenerateKubeCert.
type KubeCert struct {
	// TLSCertPEM is the PEM-encoded client certificate that kubectl presents
	// when authenticating to the kube cluster via Teleport's proxy.
	TLSCertPEM string

	// TLSKeyPEM is the corresponding private key.
	TLSKeyPEM string

	// TLSCAsPEM are the CA certs needed to verify the Teleport-fronted kube
	// API endpoint.
	TLSCAsPEM []string

	// KubeProxyAddress is the host:port kubectl should use as its server.
	// This is the Teleport proxy's ALPN listener.
	KubeProxyAddress string

	// Expires is the certificate expiry, surfaced so the kubeconfig exec
	// plugin can report an accurate expirationTimestamp.
	Expires time.Time
}

// apiClient is the subset of *teleportClient.Client that sdkClient depends on.
// Declaring it lets the implementation stay focused and documents the exact
// SDK surface in use.
type apiClient interface {
	Ping(ctx context.Context) (proto.PingResponse, error)
	GenerateUserCerts(ctx context.Context, req proto.UserCertsRequest) (*proto.Certs, error)
	Close() error
}

// sdkClient is the production Client backed by the Teleport API SDK.
type sdkClient struct {
	api          apiClient
	proxyAddress string
	username     string
}

// NewClient constructs a production Client from TeleportCredentials.
//
// It builds an mTLS connection to the Teleport proxy using the credentials'
// TLS cert/key/CA. The actual gRPC dial happens here, so NewClient requires
// connectivity to the proxy and is validated against a live cluster.
func NewClient(ctx context.Context, creds *types.TeleportCredentials) (Client, error) {
	defer perf.Track(nil, "teleport.NewClient")()

	if creds == nil {
		return nil, fmt.Errorf("%w: credentials are nil", errUtils.ErrTeleportInvalidConfig)
	}
	if creds.ProxyAddress == "" {
		return nil, fmt.Errorf("%w: credentials carry no proxy address", errUtils.ErrTeleportProxyResolution)
	}

	tlsConfig, err := tlsConfigFromCreds(creds)
	if err != nil {
		return nil, err
	}

	api, err := teleportClient.New(ctx, teleportClient.Config{
		Addrs:       []string{creds.ProxyAddress},
		Credentials: []teleportClient.Credentials{teleportClient.LoadTLS(tlsConfig)},
		DialTimeout: dialTimeout,
	})
	if err != nil {
		return nil, fmt.Errorf("%w: %w", errUtils.ErrTeleportProxyUnreachable, err)
	}

	return &sdkClient{
		api:          api,
		proxyAddress: creds.ProxyAddress,
		username:     creds.Username,
	}, nil
}

// tlsConfigFromCreds builds a *tls.Config presenting the credentials' client
// certificate and trusting the credentials' CA certs.
func tlsConfigFromCreds(creds *types.TeleportCredentials) (*tls.Config, error) {
	if creds.TLSCertPEM == "" || creds.TLSKeyPEM == "" {
		return nil, fmt.Errorf("%w: credentials carry no TLS certificate/key", errUtils.ErrTeleportInvalidConfig)
	}

	cert, err := tls.X509KeyPair([]byte(creds.TLSCertPEM), []byte(creds.TLSKeyPEM))
	if err != nil {
		return nil, fmt.Errorf("%w: invalid TLS key pair: %w", errUtils.ErrTeleportInvalidConfig, err)
	}

	pool := x509.NewCertPool()
	for _, ca := range creds.TLSCAsPEM {
		if !pool.AppendCertsFromPEM([]byte(ca)) {
			return nil, fmt.Errorf("%w: failed to parse a CA certificate", errUtils.ErrTeleportInvalidConfig)
		}
	}

	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      pool,
		MinVersion:   tls.VersionTLS12,
	}, nil
}

// Ping verifies connectivity and returns cluster authority info.
func (c *sdkClient) Ping(ctx context.Context) (*PingResponse, error) {
	defer perf.Track(nil, "teleport.sdkClient.Ping")()

	resp, err := c.api.Ping(ctx)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", errUtils.ErrTeleportProxyUnreachable, err)
	}
	return &PingResponse{
		ClusterName:     resp.ClusterName,
		ServerVersion:   resp.ServerVersion,
		ProxyPublicAddr: resp.ProxyPublicAddr,
	}, nil
}

// GenerateKubeCert issues a per-kubernetes-cluster TLS certificate.
//
// It generates a fresh key pair, requests a Kubernetes-usage certificate routed
// to the named cluster, and returns the new cert/key/CA for embedding in a
// kubeconfig entry.
func (c *sdkClient) GenerateKubeCert(ctx context.Context, req GenerateKubeCertRequest) (*KubeCert, error) {
	defer perf.Track(nil, "teleport.sdkClient.GenerateKubeCert")()

	if req.KubernetesCluster == "" {
		return nil, fmt.Errorf("%w: kubernetes cluster name is required", errUtils.ErrTeleportKubeCertGeneration)
	}

	priv, pubPEM, err := newCertKeyPair()
	if err != nil {
		return nil, err
	}

	expires := time.Now().Add(resolveTTL(req.TTL))

	certs, err := c.api.GenerateUserCerts(ctx, proto.UserCertsRequest{
		TLSPublicKey:      pubPEM,
		Username:          c.username,
		Expires:           expires,
		KubernetesCluster: req.KubernetesCluster,
		Usage:             proto.UserCertsRequest_Kubernetes,
	})
	if err != nil {
		return nil, fmt.Errorf("%w: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}

	cas := make([]string, 0, len(certs.TLSCACerts))
	for _, ca := range certs.TLSCACerts {
		cas = append(cas, string(ca))
	}

	return &KubeCert{
		TLSCertPEM:       string(certs.TLS),
		TLSKeyPEM:        string(priv.PrivateKeyPEM()),
		TLSCAsPEM:        cas,
		KubeProxyAddress: c.proxyAddress,
		Expires:          expires,
	}, nil
}

// Close releases the underlying SDK client.
func (c *sdkClient) Close() error {
	if c.api == nil {
		return nil
	}
	return c.api.Close()
}

// newCertKeyPair generates a fresh private key and returns it together with its
// PKIX-marshaled public key (the format Teleport expects for TLSPublicKey).
func newCertKeyPair() (*keys.PrivateKey, []byte, error) {
	rsaKey, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
	if err != nil {
		return nil, nil, fmt.Errorf("%w: failed to generate key: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}
	priv, err := keys.NewPrivateKey(rsaKey)
	if err != nil {
		return nil, nil, fmt.Errorf("%w: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}
	pubPEM, err := keys.MarshalPublicKey(priv.Public())
	if err != nil {
		return nil, nil, fmt.Errorf("%w: failed to marshal public key: %w", errUtils.ErrTeleportKubeCertGeneration, err)
	}
	return priv, pubPEM, nil
}

// resolveTTL parses a TTL string, falling back to defaultKubeCertTTL when empty
// or invalid.
func resolveTTL(ttl string) time.Duration {
	if ttl == "" {
		return defaultKubeCertTTL
	}
	parsed, err := time.ParseDuration(ttl)
	if err != nil || parsed <= 0 {
		return defaultKubeCertTTL
	}
	return parsed
}
